### ISSUE TITLE
Is there a way to automate the page ids

### ISSUE THREAD

**Issue by pranathivemuri** [upleveled/notion-backup#142]
Hi!

Thanks so much for the repo.

I was wondering if there is a way to automatically get page id's? 

I.e run a function or github action beforehand like exportspace and get the page id's and parse them as a json like you would need in exportblocks sections.

Is that possible?

I was going to use this script to do a cron job of backup but I was wondering if there were new pages, and their id's are not included in the blocks list then they wouldn't be backed up, is that right? Thanks in advance for your reply

**Comment by karlhorky** [comment]
You mean the "page block id" here, right? https://github.com/upleveled/notion-backup/blob/829e52d8d44c18f840f4802fffdc315091db565b/index.js#L9-L14

I haven't looked into a way to do this yet - for now I have been taking the ids of pages at the root, and then I use `recursive: true` to get all children of that. I guess you're doing this already though? You have a lot of new pages at the root always?

**Comment by pranathivemuri** [comment]
yes, I meant there. 

Yeah, there are a bunch created every day so it would need still manual updating, so I was wondering if that could be automated?
