### ISSUE TITLE
Error: The process failed with exit code  2

### ISSUE THREAD

**Issue by cattenbb** [upleveled/notion-backup#186]
Hello, I am getting this error. 

"
Run actions/setup-node@v3
  
Attempting to download 18...
Acquiring 18.14.0 - x64 from https://github.com/actions/node-versions/releases/download/18.14.0-4082410607/node-18.14.0-win32-x64.7z
Extracting ...
The process 'C:\Windows\System32\_work\_actions\actions\setup-node\v3\externals\7zr.exe' failed with exit code 2
Falling back to download directly from Node
Acquiring 18.14.0 - x64 from https://nodejs.org/dist/v18.14.0/node-v18.14.0-win-x64.7z
Extracting ...
Error: The process 'C:\Windows\System32\_work\_actions\actions\setup-node\v3\externals\7zr.exe' failed with exit code 2
"

**Comment by karlhorky** [comment]
Hmm, it seems this error is unrelated to `notion-backup`, but rather is related to using [`actions/setup-node`](https://github.com/actions/setup-node) with a Windows runner, probably this should be reported as an issue over there (or maybe there is already an issue).

Or it may be a temporary problem - you could also try re-running the workflow.
