### ISSUE TITLE
AxiosError: Request failed with status code 401

### ISSUE THREAD

**Issue by juba0x00** [upleveled/notion-backup#204]
- I was using this project since it was written in Python and JS, it stopped working, I noticed that the project had significant changes, so I forked it again. 
-  I think the notion token format has been changed, I don't know what should I store in `NOTION_TOKEN` secret.
- my token (after obfuscation to keep it confidential 😉) 
```
oken_v2=v02%3Auser_token_or_cookies%3APlxqlqoPDGsBleNr-WbCZxfjeDp_fAeAqNCAkxusGEuoPBUItPVnIEQKytdXKlltQKnUbTmvsQkYdfBRsYzGX-uvWMbmsaYgORLBM_ZilAXmDqzlSOKGnMvlXilEHZjtPr_j;
```
# things I tried
1. I tried to store the whole value without any changes (from `=` to `;`).
2. I tried to URL decode and use it.
3. I tried to use the token after `user_token_or_cookies:`

- all the previous tires do not work and I can't export anything
- `Link and check types` action finishes successfully, but the `Export Notion Blocks and Commit to Git` return exit code 1 in `Run backup script` step
- If the logs do not contain any sensitive data and sharing it will help solve the problem, tell me I'll share it.

**Comment by karlhorky** [comment]
Can you show the error message from the logs associated with the "exit code 1"? Unfortunately "exit code 1" does not tell us much about the error.

One currently known error (we're currently working on it) is the `AxiosError: Request failed with status code 403` error, which is also documented in this issue in `notion-guardian`, which this project is based off of:

- https://github.com/richartkeil/notion-guardian/issues/11

If you think that this is the problem, maybe you could edit your issue title and description above to be more clear about these details. We can leave this issue open to track the problem.

**Comment by juba0x00** [comment]
- AxiosError: Request failed with status code 401
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
[AxiosError: Request failed with status code 401] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: [Function: FormData] {
        LINE_BREAK: '\r\n',
        DEFAULT_CONTENT_TYPE: 'application/octet-stream'
      }
    },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Cookie: 'token_v2=***',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 1[9](https://github.com/juba0x00/Notion-Backup/actions/runs/4634485957/jobs/8205118912#step:5:10)7
    },
    baseURL: 'https://www.notion.so/api/v3',
    method: 'post',
    url: 'enqueueTask',
    data: '{"task":{"eventName":"exportBlock","request":{"blockId":"2cbcf55b-3da7-4c63-8ac0-73f47b1fdb06","exportOptions":{"exportType":"markdown","locale":"en","timeZone":"Europe/Vienna"},"recursive":true}}}'
  }
```

**Comment by karlhorky** [comment]
Thanks for the update! This is probably unrelated to the current HTTP `403` error.

Probably your `NOTION_TOKEN` is not set to the correct value - like [the instructions](https://github.com/upleveled/notion-backup#setup) and [this article](https://archive.ph/b5mgg#selection-575.0-575.9) state, you use the full value after `token_v2=`. This appears to be still working.

**Comment by juba0x00** [comment]
As I mentioned: 
> # things I tried
> 1. I tried to store the whole value without any changes (from `=` to `;`).
> 2. I tried to URL decode and use it.
> 3. I tried to use the token after `user_token_or_cookies:`
> 
> * all the previous tires do not work and I can't export anything
> * `Link and check types` action finishes successfully, but the `Export Notion Blocks and Commit to Git` return exit code 1 in `Run backup script` step
> * If the logs do not contain any sensitive data and sharing it will help solve the problem, tell me I'll share it.

I have tried these, and I tried them again, but nothing worked.
- I don't remember that `NOTION_TOKEN` was in this format `v02%3Auser_token_or_cookies%3Arandom_characters`
-  I don't know what is the problem.

**Comment by karlhorky** [comment]
In case you receive HTTP 400 errors with your existing version of the backup script (not 100% the same as `401` or `403` errors, but in the same error category), then you will probably want to update the script again:

- https://github.com/upleveled/notion-backup/pull/205#issuecomment-1510404263
