### ISSUE TITLE
AxiosError: Request failed with status code 401

### ISSUE THREAD

**Issue by alice-rosen** [upleveled/notion-backup#218]
Hi @karlhorky,

For the past ~5 days, the backups have been failing with this error:

`AxiosError: Request failed with status code 401`

Here are the details (santised). Do you have any idea what may be causing the problem - has anything changed in the last few days? Have you experienced this issue yourself?

```
headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Cookie: 'token_v2=***',
      'User-Agent': 'axios/1.3.5',
      'Content-Length': '251',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'https://www.notion.so/api/v3',
    method: 'post',
    url: 'enqueueTask',
    data: '{"task":{"eventName":"exportBlock","request":{"block":{"id":"xxxxxxxx-xxxx-x[xx](https://github.com/alice-rosen/notion-dphil-automated/actions/runs/xxxxxxxxxx/jobs/xxxxxxxxxx#step:6:43)x-xxxx-xxxxxxxxxxxx","spaceId":"xxxxxxxx-xxxx-[xx](https://github.com/alice-rosen/notion-dphil-automated/actions/runs/xxxxxxxxxx/jobs/xxxxxxxxxx#step:6:45)xx-xxxx-xxxxxxxxxx"},"exportOptions":{"exportType":"markdown","locale":"en","timeZone":"Europe/Vienna"},"recursive":true}}}'
  },
```

``` 
 response: {
    status: 401,
    statusText: 'Unauthorized',
```

Please let me know if you have any suggestions :)

**Comment by karlhorky** [comment]
Our (daily) backups have been working, so I don't think it's a problem with the script or Notion.

Often 401 means that the token is invalid - eg. the Notion tokens do expire after some time. Maybe try logging into Notion again and copying your token out into your GitHub Actions secret, as described in step 3 of [the setup intructions](https://github.com/upleveled/notion-backup#setup)?

**Comment by alice-rosen** [comment]
That worked, thanks @karlhorky! Now I know what to try next time that happens :)
