### ISSUE TITLE
Can not open website: https://archive.ph/b5mgg

### ISSUE THREAD

**Issue by Springder** [upleveled/notion-backup#224]
I can't access [tutorial](https://archive.ph/b5mgg) for setting NOTION_TOKEN.

**Comment by karlhorky** [comment]
Not sure why archive.ph is not working for you (works for me and others I've asked) but I added a link to the Medium article here: https://artur-en.medium.com/automated-notion-backups-f6af4edc298d

**Comment by Springder** [comment]
I don't know why. But I can access the latter website. Thank you very much!
