### ISSUE TITLE
Feature Request: Improving File Name Readability in Notion Backups

### ISSUE THREAD

**Issue by juba0x00** [upleveled/notion-backup#230]
**Issue Title:** 
Improving File Name Readability in Notion Backups

**Issue Description:**
As a Notion user, I often find it challenging to manage and organize my backup files, especially when the default naming conventions have a random 32-character hexadecimal. This can make it difficult to navigate and maintain my backup data effectively.

**Feature Request:**
I want to propose an enhancement to our Notion backup system by implementing a "Notion Backup Renamer" feature. This feature should:

1. Rename all files and directories within the Notion backup to more human-readable names.
2. Update links within Notion content to reflect the renamed files and directories.
3. Handle cases of repeated names by appending unique identifiers.

- **Actually, I did this feature, and I'll create a pull request.**

**Use Case:**
Imagine I have a directory structure in my Notion backup like this:

```
├── exports
|   ├── AD Methodology
|   │   ├── Active Directory Methodology b9ee5c899e2f4e06bb9c97b4d2cabccc
|   │   │   ├── Credentials Harvesting b712490fbb3b4bfa86a1b842aa2d70d7.md
|   │   │   ├── Enumeration f60ee762a10d42d4b71fdf738ec4d488
|   │   │   │   ├── Untitled 1.png
|   │   │   │   └── Untitled.png
|   │   │   ├── Enumeration f60ee762a10d42d4b71fdf738ec4d488.md
|   │   │   ├── Lateral Movement and Pivoting 3cde086d845d479f9148816f925758cf
|   │   │   │   ├── Credentials Harvesting 221e548f4db748d7bb8aa89c5e66e591.md
|   │   │   │   ├── GetUserSPNs.py
|   │   │   │   ├── impacket-0.10.0.tar.gz
|   │   │   │   ├── Untitled 1.png
|   │   │   │   ├── Untitled 2.png
|   │   │   │   ├── Untitled 3.png
|   │   │   │   └── Untitled.png
|   │   │   ├── Lateral Movement and Pivoting 3cde086d845d479f9148816f925758cf.md
|   │   │   ├── Persisting Active Directory 202e1bfce9eb4309a067d44ff86c25fc
|   │   │   │   ├── Untitled 1.png
|   │   │   │   ├── Untitled 2.png
|   │   │   │   └── Untitled.png
|   │   │   └── Persisting Active Directory 202e1bfce9eb4309a067d44ff86c25fc.md
|   │   └── Active Directory Methodology b9ee5c899e2f4e06bb9c97b4d2cabccc.md
|   ├── DFIR
|   │   ├── DFIR 96557f433ade4e789a339fc088772798
|   │   │   ├── Linux Forensics a847cd1df8a34940ae009a5f18f166aa.md
|   │   │   ├── Memory Forensics ca4febfe719944199d6ea454d47e5ee3
|   │   │   │   ├── CheatSheet_v2.4.pdf
|   │   │   │   └── Untitled.png
|   │   │   ├── Memory Forensics ca4febfe719944199d6ea454d47e5ee3.md
|   │   │   └── Windows Forensics 16ab95e347a14f55a70e18e1641a3dca.md
|   │   └── DFIR 96557f433ade4e789a339fc088772798.md
<SNIP>
```

After applying the "Notion Backup Renamer" feature, the structure would look like this:

```
├── exports
│   ├── AD Methodology
│   │   ├── Active Directory Methodology
│   │   │   ├── Credentials Harvesting.md
│   │   │   ├── Enumeration
│   │   │   │   ├── Untitled 1.png
│   │   │   │   └── Untitled.png
│   │   │   ├── Enumeration.md
│   │   │   ├── Lateral Movement and Pivoting
│   │   │   │   ├── Credentials Harvesting.md
│   │   │   │   ├── GetUserSPNs.py
│   │   │   │   ├── impacket-0.10.0.tar.gz
│   │   │   │   ├── Untitled 1.png
│   │   │   │   ├── Untitled 2.png
│   │   │   │   ├── Untitled 3.png
│   │   │   │   └── Untitled.png
│   │   │   ├── Lateral Movement and Pivoting.md
│   │   │   ├── Persisting Active Directory
│   │   │   │   ├── Untitled 1.png
│   │   │   │   ├── Untitled 2.png
│   │   │   │   └── Untitled.png
│   │   │   └── Persisting Active Directory.md
│   │   └── Active Directory Methodology.md
│   ├── DFIR
│   │   ├── DFIR
│   │   │   ├── Linux Forensics.md
│   │   │   ├── Memory Forensics
│   │   │   │   ├── CheatSheet_v2.4.pdf
│   │   │   │   └── Untitled.png
│   │   │   ├── Memory Forensics.md
│   │   │   └── Windows Forensics.md
│   │   └── DFIR.md
<SNIP>
```

**Expected Benefits:**
- Improved organization and readability of backup data.
- Reduced confusion when navigating backups with similar or duplicate names.
- Enhanced usability for users with large and complex Notion data.

**Proposed Solution:**
1. Implement the "Notion Backup Renamer" feature as described above.

**Acceptance Criteria:**
- The script successfully renames files and directories.
- Links within Notion content are updated to reflect the renamed elements.
- Duplicates produced by removing the hex values names are handled by appending small unique identifiers.
- Documentation is created and added to the repository.

**Comment by karlhorky** [comment]
First of all, thanks for taking the time to create the script and the PR, good work!

However, the idea of `notion-backup` is to keep the format of whatever is coming from Notion, to avoid any conflicts or mismatches that may occur.

So I'm going to close this one - if you create a separate repo with only the script in it, you could create a PR to update the readme of `notion-backup` to link to it, since it builds off of `notion-backup`.

**Comment by juba0x00** [comment]
@karlhorky , Firstly thanks for your appreciation.
I think it would be a good idea if you add a condition to run the rename script, If users want to use this feature make a boolean variable true.
we can make it disabled by default.
it's all up to you, I just want to help.

**Comment by karlhorky** [comment]
From a user perspective, it seems like a good idea. However, from a maintainer perspective (from the perspective of me, who has to deal with any problems and bugs with the renaming), I don't want to maintain this.

But totally fine with me if you want to, in your own repo / project!
