### ISSUE TITLE
"Waiting 1 second before polling again..."

### ISSUE THREAD

**Issue by j10sanders** [upleveled/notion-backup#285]
Love this project - thanks for putting it together. Trying to debug why mine isn't working - I added the secret and edited my index to include the space-id.

https://github.com/j10sanders/notion_backup/actions/runs/10342466010/job/28625450837

**Comment by karlhorky** [comment]
Hi @j10sanders, thanks for the warm words ❤️

The link above is broken unfortunately (or maybe private?). Can you provide some further logs? (make sure to not expose any private data)

The "Waiting x seconds before polling again..." message occurs when the polling is being rate limited - it should not cause the script to fail in my experience.

**Comment by j10sanders** [comment]
Sure! Thanks for the response.

You can see it just ends after retrying for a while: 
<img width="606" alt="Screenshot 2024-08-11 at 6 30 24 PM" src="https://github.com/user-attachments/assets/44357d92-387f-463b-a8a0-86245fa0eded">

<img width="780" alt="Screenshot 2024-08-11 at 6 33 51 PM" src="https://github.com/user-attachments/assets/ad0f20f3-bde6-4bd8-8ed8-c640191eb594">


All I edited in the index file is the space-id, so it looks like this:

```const blocks = [
  {
    // Find the page block ID by either:
    // 1. Copying the alphanumeric part at the end of the Notion
    //    page URL and separate it with dashes in the same format
    //    as below (number of characters between dashes:
    //    8-4-4-4-12)
    // 2. Inspecting network requests in the DevTools
    id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    // Find the space ID associated with a block by running this
    // in the DevTools Console while on the page you want to
    // export:
    // ```
    // $('img[src*="spaceId="]').src.replace(/^.+&spaceId=([^&]+)&.+$/, '$1')
    // ```
    spaceId: <MY SPACE ID AS A STRING>,
    // Choose a directory name for your export to appear in the
    // `exports` folder
    dirName: 'notion-page-a',
    // Should all of the subpages also be exported?
    recursive: false,
  },
];```

**Comment by karlhorky** [comment]
Ah, there is a relevant error message in your second screenshot - your backup is taking longer than 35 minutes.

You can increase the timeout in the workflow yaml.

**Comment by karlhorky** [comment]
@j10sanders hope my reply above helped!

I'll close this issue for now - if you have any further questions or anything you can either continue replying here or open a new issue
